### ISSUE TITLE
An error occurs when using partial assignment with the splat operator

### ISSUE THREAD

**Issue by koic** [kddnewton/parser-prism#11]
"Partial assignment with the splat operator" syntax that can be parsed by the Parser gem results in an error with parser-prism:

## Expected: The Parser gem

No errors and it can be parsed:

```console
$ ruby-parse --33 -e 'expression, = *node'
(masgn
  (mlhs
    (lvasgn :expression))
  (array
    (splat
      (send nil :node))))
```

## Actual: parser-prism

The following error occurs:

```console
% ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin22]
$ ruby -rparser/prism -e 'p Parser::Prism.parse("expression, = *node")'
/Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-prism-0.1.0/lib/parser/prism/compiler.rb:758:in `visit_implicit_rest_node': Cannot directly compile implicit rest nodes (RuntimeError)
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/node.rb:8058:in `accept'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/compiler.rb:34:in `block in visit_all'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/compiler.rb:34:in `map'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/compiler.rb:34:in `visit_all'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-prism-0.1.0/lib/parser/prism/compiler.rb:1083:in `visit_multi_write_node'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/node.rb:12275:in `accept'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/compiler.rb:34:in `block in visit_all'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/compiler.rb:34:in `map'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/compiler.rb:34:in `visit_all'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-prism-0.1.0/lib/parser/prism/compiler.rb:1407:in `visit_statements_node'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/node.rb:15784:in `accept'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-prism-0.1.0/lib/parser/prism/compiler.rb:1231:in `visit_program_node'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/prism-0.19.0/lib/prism/node.rb:13913:in `accept'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-prism-0.1.0/lib/parser/prism.rb:109:in `build_ast'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-prism-0.1.0/lib/parser/prism.rb:31:in `parse'
        from /Users/koic/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/parser-3.3.0.5/lib/parser/base.rb:33:in `parse'
        from -e:1:in `<main>'
```

The same error also occurs with the combination of Ruby 3.0 and parser-prism.

**Comment by kddnewton** [comment]
Hey @koic - thanks for the report!

Over the weekend I merged this gem directly into prism itself, so I fixed this over there. Could you give it a shot over on that repository?

**Comment by koic** [comment]
Great news! This issue has been resolved in `Prism::Translation::Parser`. Thank you!
